slistexe: slist.o slistapp.o slistimp.o
	c++ -o slistexe slist.o slistapp.o slistimp.o
slist.o: slist.cpp
	c++ -c slist.cpp
slistapp.o.o: slistapp.cpp
	c++ -c slistapp.cpp
slistimp.o: slistimp.cpp
	c++ -c slistimp.cpp

